# it's this way that we up an image of postgres in docker with compose
# docker compose up -d
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=devpass
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
        
volumes:
  pgdata: